// <auto-generated />
using System;
using FinanClickApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanClickApi.Migrations
{
    [DbContext(typeof(FinanclickDbContext))]
    [Migration("20240803051513_pagosYamortizaciones")]
    partial class pagosYamortizaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetalleModuloUsuario", b =>
                {
                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdModulo", "IdUsuario")
                        .HasName("PK__DetalleM__BC4708EC21F1C8DD");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DetalleModuloUsuario", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Amortizacion", b =>
                {
                    b.Property<int>("IdAmortizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAmortizacion"));

                    b.Property<decimal>("Capital")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Capital");

                    b.Property<int>("Estatus")
                        .HasColumnType("INT")
                        .HasColumnName("Estatus");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaFin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("IdCredito")
                        .HasColumnType("INT")
                        .HasColumnName("IdCredito");

                    b.Property<decimal>("InteresMasIva")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("InteresMasIva");

                    b.Property<decimal>("InteresMoratorio")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("InteresMoratorio");

                    b.Property<decimal>("InteresOrdinario")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("InteresOrdinario");

                    b.Property<decimal>("Iva")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("IVA");

                    b.Property<decimal>("PagoFijo")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PagoFijo");

                    b.Property<decimal>("SaldoInsoluto")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SaldoInsoluto");

                    b.HasKey("IdAmortizacion")
                        .HasName("PK__Amortiza__8D928C9884C966EE");

                    b.HasIndex("IdCredito");

                    b.ToTable("Amortizacion", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Aval", b =>
                {
                    b.Property<int>("IdAval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAval");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAval"));

                    b.Property<int?>("IdCredito")
                        .HasColumnType("int")
                        .HasColumnName("idCredito");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int?>("IdPersonaMoral")
                        .HasColumnType("int")
                        .HasColumnName("idPersonaMoral");

                    b.HasKey("IdAval")
                        .HasName("PK__Aval__D8A6A80225CFEA8D");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdPersonaMoral");

                    b.ToTable("Aval", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.CatConcepto", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcepto"));

                    b.Property<int?>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IVA");

                    b.Property<string>("NombreConcepto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoValor")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdConcepto")
                        .HasName("PK__CatConce__367401534DDC30ED");

                    b.ToTable("CatConceptos");
                });

            modelBuilder.Entity("FinanClickApi.Models.CatalogoDocumento", b =>
                {
                    b.Property<int>("IdCatalogoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCatalogoDocumento"));

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCatalogoDocumento")
                        .HasName("PK__Catalogo__661C085CC0A69FBB");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("CatalogoDocumentos");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    b.Property<string>("RegimenFiscal")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D594664253D4D0E5");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredito"));

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaActivacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaFirma")
                        .HasColumnType("date");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdPromotor")
                        .HasColumnType("int");

                    b.Property<decimal>("InteresMoratorio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InteresOrdinario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("NumPagos")
                        .HasColumnType("int");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCredito")
                        .HasName("PK__Credito__EF6108CB209BE43B");

                    b.HasIndex("IdProducto");

                    b.ToTable("Credito", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.DatosClienteFisica", b =>
                {
                    b.Property<int>("IdClienteFisica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClienteFisica"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.HasKey("IdClienteFisica")
                        .HasName("PK__DatosCli__0F2855A92E6905D0");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPersona");

                    b.ToTable("DatosClienteFisica", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.DatosClienteMoral", b =>
                {
                    b.Property<int>("IdClienteMoral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClienteMoral"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersonaMoral")
                        .HasColumnType("int");

                    b.Property<string>("NombreRepLegal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RfcrepLegal")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("RFCRepLegal");

                    b.HasKey("IdClienteMoral")
                        .HasName("PK__DatosCli__5A0ACC3D6EF100FC");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPersonaMoral");

                    b.ToTable("DatosClienteMoral", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.DocumentosCliente", b =>
                {
                    b.Property<int>("IdDocumentoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentoCliente"));

                    b.Property<string>("DocumentoBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.HasKey("IdDocumentoCliente")
                        .HasName("PK__Document__232F08451D75BCC3");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDocumento");

                    b.ToTable("DocumentosCliente", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaConstitucion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date");

                    b.Property<string>("FolioMercantil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreNotario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreRepresentanteLegal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumExterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumInterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroEscritura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroEscrituraRepLeg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroNotario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEmpresa")
                        .HasName("PK__Empresa__5EF4033EED026D14");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdModulo")
                        .HasName("PK__Modulo__D9F15315EB19A4AB");

                    b.ToTable("Modulo", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Obligado", b =>
                {
                    b.Property<int>("IdObligado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idObligado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObligado"));

                    b.Property<int?>("IdCredito")
                        .HasColumnType("int")
                        .HasColumnName("idCredito");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int?>("IdPersonaMoral")
                        .HasColumnType("int")
                        .HasColumnName("idPersonaMoral");

                    b.HasKey("IdObligado")
                        .HasName("PK__Obligado__E088162F78AC3B83");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdPersonaMoral");

                    b.ToTable("Obligado", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("Estatus")
                        .HasColumnType("INT")
                        .HasColumnName("Estatus");

                    b.Property<DateOnly>("FechaAplicacion")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaPago");

                    b.Property<int>("IdCredito")
                        .HasColumnType("INT")
                        .HasColumnName("IdCredito");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("MontoPago");

                    b.HasKey("IdPago")
                        .HasName("PK__Pago__FC851A3A66103805");

                    b.HasIndex("IdCredito");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CiudadResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClaveElector")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("CURP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoNacimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadoResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreConyuge")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumExterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumInterior")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaisNacimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaisResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RegimenMatrimonial")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("RFC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdPersona")
                        .HasName("PK__Persona__2EC8D2AC779D8E92");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.PersonaMoral", b =>
                {
                    b.Property<int>("IdPersonaMoral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonaMoral"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CiudadRegistro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CiudadResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadoRegistro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadoResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaConstitucion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaRppc")
                        .HasColumnType("date")
                        .HasColumnName("FechaRPPC");

                    b.Property<string>("FolioMercantil")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreNotario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumEscritura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumExterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumInterior")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumNotario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaisRegistro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaisResidencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RazonComercial")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("RFC");

                    b.HasKey("IdPersonaMoral")
                        .HasName("PK__PersonaM__D333C18CD1FEDAC6");

                    b.ToTable("PersonaMoral", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("AplicacionDePagos")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdDetalleProductos")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal?>("InteresAnual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("InteresMoratorio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IVA");

                    b.Property<string>("MetodoCalculo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NumPagos")
                        .HasColumnType("int");

                    b.Property<string>("PagoAnticipado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Periodicidad")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Reca")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SubMetodo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__0988921069CC884B");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584C5977DB14");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF975403CE1B");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.UsuarioCliente", b =>
                {
                    b.Property<int>("IdUsuarioCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioCliente"));

                    b.Property<string>("Contrasenia")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdUsuarioCliente")
                        .HasName("PK__UsuarioC__B128AB53C227D146");

                    b.HasIndex("IdCliente");

                    b.ToTable("UsuarioCliente", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Modelss.DetalleProducto", b =>
                {
                    b.Property<int>("IdDetalleProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleProductos"));

                    b.Property<int?>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdConcepto")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IVA");

                    b.Property<string>("TipoValor")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdDetalleProductos")
                        .HasName("PK__DetalleP__C1FCE8FD435910E6");

                    b.HasIndex("IdConcepto");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetalleProductos");
                });

            modelBuilder.Entity("DetalleModuloUsuario", b =>
                {
                    b.HasOne("FinanClickApi.Models.Modulo", null)
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleMo__IdMod__412EB0B6");

                    b.HasOne("FinanClickApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleMo__IdUsu__4222D4EF");
                });

            modelBuilder.Entity("FinanClickApi.Models.Amortizacion", b =>
                {
                    b.HasOne("FinanClickApi.Models.Credito", "IdCreditoNavigation")
                        .WithMany("Amortizacions")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Credito_Amortizacion_72C60C4A");

                    b.Navigation("IdCreditoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Aval", b =>
                {
                    b.HasOne("FinanClickApi.Models.Credito", "IdCreditoNavigation")
                        .WithMany("Avals")
                        .HasForeignKey("IdCredito")
                        .HasConstraintName("FK__Aval__idCredito__32AB8735");

                    b.HasOne("FinanClickApi.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Avals")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK_Aval_Persona");

                    b.HasOne("FinanClickApi.Models.PersonaMoral", "IdPersonaMoralNavigation")
                        .WithMany("Avals")
                        .HasForeignKey("IdPersonaMoral")
                        .HasConstraintName("FK_Aval_PersonaMoral");

                    b.Navigation("IdCreditoNavigation");

                    b.Navigation("IdPersonaMoralNavigation");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.CatalogoDocumento", b =>
                {
                    b.HasOne("FinanClickApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("CatalogoDocumentos")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Cliente__idEmpresa_C4TEMPR354");

                    b.Navigation("IdEmpresaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.HasOne("FinanClickApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Cliente__idEmpre__44FF419A");

                    b.Navigation("IdEmpresaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Credito", b =>
                {
                    b.HasOne("FinanClickApi.Models.Producto", "IdProductoNavigation")
                        .WithMany("Creditos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Credito__IdProdu__2DE6D218");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.DatosClienteFisica", b =>
                {
                    b.HasOne("FinanClickApi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("DatosClienteFisicas")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__DatosClie__IdCli__52593CB8");

                    b.HasOne("FinanClickApi.Models.Persona", "IdPersonaNavigation")
                        .WithMany("DatosClienteFisicas")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK__DatosClie__IdPer__5165187F");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.DatosClienteMoral", b =>
                {
                    b.HasOne("FinanClickApi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("DatosClienteMorals")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__DatosClie__IdCli__5629CD9C");

                    b.HasOne("FinanClickApi.Models.PersonaMoral", "IdPersonaMoralNavigation")
                        .WithMany("DatosClienteMorals")
                        .HasForeignKey("IdPersonaMoral")
                        .HasConstraintName("FK__DatosClie__IdPer__5535A963");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPersonaMoralNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.DocumentosCliente", b =>
                {
                    b.HasOne("FinanClickApi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("DocumentosClientes")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Documento__IdCli__4AB81AF0");

                    b.HasOne("FinanClickApi.Models.CatalogoDocumento", "IdDocumentoNavigation")
                        .WithMany("DocumentosClientes")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("FK__Documento__IdDoc__49C3F6B7");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDocumentoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Obligado", b =>
                {
                    b.HasOne("FinanClickApi.Models.Credito", "IdCreditoNavigation")
                        .WithMany("Obligados")
                        .HasForeignKey("IdCredito")
                        .HasConstraintName("FK__Obligado__idCred__37703C52");

                    b.HasOne("FinanClickApi.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Obligados")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK_Obligado_Persona");

                    b.HasOne("FinanClickApi.Models.PersonaMoral", "IdPersonaMoralNavigation")
                        .WithMany("Obligados")
                        .HasForeignKey("IdPersonaMoral")
                        .HasConstraintName("FK_Obligado_PersonaMoral");

                    b.Navigation("IdCreditoNavigation");

                    b.Navigation("IdPersonaMoralNavigation");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Pago", b =>
                {
                    b.HasOne("FinanClickApi.Models.Credito", "IdCreditoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Credito_Pago_72C60C4A");

                    b.Navigation("IdCreditoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Usuario", b =>
                {
                    b.HasOne("FinanClickApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Usuario__IdEmpre__3E52440B");

                    b.HasOne("FinanClickApi.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuario__IdRol__3D5E1FD2");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.UsuarioCliente", b =>
                {
                    b.HasOne("FinanClickApi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("UsuarioClientes")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__UsuarioCl__IdCli__72C60C4A");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Modelss.DetalleProducto", b =>
                {
                    b.HasOne("FinanClickApi.Models.CatConcepto", "IdConceptoNavigation")
                        .WithMany("DetalleProductos")
                        .HasForeignKey("IdConcepto")
                        .HasConstraintName("FK__DetallePr__IdCon__18EBB532");

                    b.HasOne("FinanClickApi.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleProductos")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__DetallePr__IdPro__17F790F9");

                    b.Navigation("IdConceptoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.CatConcepto", b =>
                {
                    b.Navigation("DetalleProductos");
                });

            modelBuilder.Entity("FinanClickApi.Models.CatalogoDocumento", b =>
                {
                    b.Navigation("DocumentosClientes");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.Navigation("DatosClienteFisicas");

                    b.Navigation("DatosClienteMorals");

                    b.Navigation("DocumentosClientes");

                    b.Navigation("UsuarioClientes");
                });

            modelBuilder.Entity("FinanClickApi.Models.Credito", b =>
                {
                    b.Navigation("Amortizacions");

                    b.Navigation("Avals");

                    b.Navigation("Obligados");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FinanClickApi.Models.Empresa", b =>
                {
                    b.Navigation("CatalogoDocumentos");

                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FinanClickApi.Models.Persona", b =>
                {
                    b.Navigation("Avals");

                    b.Navigation("DatosClienteFisicas");

                    b.Navigation("Obligados");
                });

            modelBuilder.Entity("FinanClickApi.Models.PersonaMoral", b =>
                {
                    b.Navigation("Avals");

                    b.Navigation("DatosClienteMorals");

                    b.Navigation("Obligados");
                });

            modelBuilder.Entity("FinanClickApi.Models.Producto", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("DetalleProductos");
                });

            modelBuilder.Entity("FinanClickApi.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
