// <auto-generated />
using System;
using FinanClickApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanClickApi.Migrations
{
    [DbContext(typeof(FinanclickDbContext))]
    [Migration("20240724003011_AddTablesDocuments")]
    partial class AddTablesDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetalleModuloUsuario", b =>
                {
                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdModulo", "IdUsuario")
                        .HasName("PK__DetalleM__BC4708ECC48CFC34");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_DetalleModuloUsuario_IdUsuario");

                    b.ToTable("DetalleModuloUsuario", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.CatalogoDocumento", b =>
                {
                    b.Property<int>("IdCatalogoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCatalogoDocumento")
                        .HasName("PK__Catalogo__661C085CFFF601D2");

                    b.ToTable("CatalogoDocumentos");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D594664233EE2C82");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.DocumentosCliente", b =>
                {
                    b.Property<int>("IdDocumentoCliente")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.HasKey("IdDocumentoCliente")
                        .HasName("PK__Document__232F0845AB0DD62B");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDocumento");

                    b.ToTable("DocumentosCliente", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaConstitucion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date");

                    b.Property<string>("FolioMercantil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NombreNotario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreRepresentanteLegal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumExterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumInterior")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroEscritura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroEscrituraRepLeg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroNotario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEmpresa")
                        .HasName("PK__Empresa__5EF4033EF3A3FD3B");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdModulo")
                        .HasName("PK__Modulo__D9F153151E446F3E");

                    b.ToTable("Modulo", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584C90796678");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("FinanClickApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF9749BA4FAE");

                    b.HasIndex(new[] { "IdEmpresa" }, "IX_Usuario_IdEmpresa");

                    b.HasIndex(new[] { "IdRol" }, "IX_Usuario_IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("DetalleModuloUsuario", b =>
                {
                    b.HasOne("FinanClickApi.Models.Modulo", null)
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleMo__IdMod__46E78A0C");

                    b.HasOne("FinanClickApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleMo__IdUsu__47DBAE45");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.HasOne("FinanClickApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Cliente__IdEmpre__4AB81AF0");

                    b.Navigation("IdEmpresaNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.DocumentosCliente", b =>
                {
                    b.HasOne("FinanClickApi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("DocumentosClientes")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Documento__IdCli__5070F446");

                    b.HasOne("FinanClickApi.Models.CatalogoDocumento", "IdDocumentoNavigation")
                        .WithMany("DocumentosClientes")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("FK__Documento__IdDoc__4F7CD00D");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDocumentoNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.Usuario", b =>
                {
                    b.HasOne("FinanClickApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Usuario__IdEmpre__440B1D61");

                    b.HasOne("FinanClickApi.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuario__IdRol__4316F928");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("FinanClickApi.Models.CatalogoDocumento", b =>
                {
                    b.Navigation("DocumentosClientes");
                });

            modelBuilder.Entity("FinanClickApi.Models.Cliente", b =>
                {
                    b.Navigation("DocumentosClientes");
                });

            modelBuilder.Entity("FinanClickApi.Models.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FinanClickApi.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
